name: CI

on: 
  workflow_dispatch:

env:

  ONEAPI_COMPILER_URL: |
    https://registrationcenter-download.intel.com/akdlm/IRC_NAS/74587994-3c83-48fd-b963-b707521a63f4/l_dpcpp-cpp-compiler_p_2024.2.1.79_offline.sh
  ONEAPI_COMPILER_SH: |
    l_dpcpp-cpp-compiler_p_2024.2.1.79_offline.sh

  ACPP_COMPILER_URL: |
    https://github.com/AdaptiveCpp/AdaptiveCpp.git
  ACPP_INSTALL_PREFIX: |
    /opt/adaptivecpp/

  LLVM_VERSION: 16
  LLVM_INSTALL_PREFIX: |
    /usr/lib/llvm-$LLVM_VERSION/
  CLANG_INSTALL_PREFIX: |
    /usr/lib/llvm-$LLVM_VERSION/include/clang/

jobs:

  AdaptiveCpp_ACPP:
    runs-on: ubuntu-20.04

    steps:

      - name: Install AdaptiveCpp Compiler Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libboost-all-dev
          sudo wget https://apt.llvm.org/llvm.sh
          sudo chmod +x llvm.sh
          sudo ./llvm.sh $LLVM_VERSION
          sudo apt-get install -y libclang-$LLVM_VERSION-dev \
                                  clang-tools-$LLVM_VERSION \
                                  libomp-$LLVM_VERSION-dev \
                                  llvm-$LLVM_VERSION-dev \
                                  lld-$LLVM_VERSION

      - name: Install AdaptiveCpp Compiler
        run: |
          ls -R /usr/lib/llvm-16/include/ 1>&2
          $(which clang++$LLVM_VERSION)
          git clone https://github.com/AdaptiveCpp/AdaptiveCpp
          cd AdaptiveCpp
          mkdir build && cd build
          cmake -DCMAKE_INSTALL_PREFIX=$ACPP_INSTALL_PREFIX \
                -DCLANG_EXECUTABLE_PATH=$(which clang++$LLVM_VERSION) \
                -DCLANG_INCLUDE_PATH=$CLANG_INSTALL_PREFIX \
                ..
          sudo make install
        
      - name: Checkout votess repository
        uses: actions/checkout@v2

      - name: Build votess
        run: |
          sh make.sh

      - name: Test votess
        run: |
          ./bin/test ~[ignore] --abort --durations yes --warn NoAssertions

  OneAPI_ICPX:
    runs-on: ubuntu-20.04
    steps:

      - name: Cache Oneapi Compiler
        uses: actions/cache@v3
        with:
          path: /opt/intel/oneapi/
          key: ${{ runner.os }}-oneapi-${{ hashFiles('$ONEAPI_COMPILER_SH') }}
          restore-keys: 
            ${{ runner.os }}-oneapi-

      - name: Install OneAPI Compiler
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget $ONEAPI_COMPILER_URL
          sudo sh $ONEAPI_COMPILER_SH-a \
          --silent --cli --eula accept --install-dir /opt/intel/oneapi/
      
      - name: Checkout votess repository
        uses: actions/checkout@v2

      - name: Build votess
        run: |
          source /opt/intel/oneapi/setvars.sh
          sh make.sh

      - name: Test votess
        run: |
          source /opt/intel/oneapi/setvars.sh
          ./bin/test ~[ignore] --abort --durations yes --warn NoAssertions
