name: CI

on: 
  workflow_dispatch:

env:
  ONEAPI_COMPILER_URL: |
    https://registrationcenter-download.intel.com/akdlm/IRC_NAS/74587994-3c83-48fd-b963-b707521a63f4/l_dpcpp-cpp-compiler_p_2024.2.1.79_offline.sh
  ONEAPI_COMPILER_INSTALL: |
    l_dpcpp-cpp-compiler_p_2024.2.1.79_offline.sh

jobs:
  Intel_OneAPI_ICPX:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up cache for installed compiler
        id: oneapi-cache
        uses: actions/cache@v2
        with:
          path: ./oneapi_cache
          key: ${{ runner.os }}-oneapi-installed-${{ hashFiles('**/path_to_compiler_installer') }}

      - name: Restore Compiler to /opt/intel/oneapi
        if: steps.oneapi-cache.outputs.cache-hit == 'true'
        run: |
          sudo mkdir -p /opt/intel
          sudo mv ./oneapi_cache /opt/intel/oneapi

      - name: Download Compiler installer
        if: steps.oneapi-cache.outputs.cache-hit != 'true'
        run: |
          wget $ONEAPI_COMPILER_URL -O compiler_installer.sh

      - name: Install Compiler
        if: steps.oneapi-cache.outputs.cache-hit != 'true'
        run: |
          sudo sh ./compiler_installer.sh -a \
          --silent --cli --eula accept --install-dir ./oneapi_cache

      - name: Move Installed Compiler to Cache Directory
        if: steps.oneapi-cache.outputs.cache-hit != 'true'
        run: |
          sudo mv /opt/intel/oneapi ./oneapi_cache

      - name: Checkout votess
        uses: actions/checkout@v2

      - name: Build votess
        run: |
          source /opt/intel/oneapi/setvars.sh
          echo "Using compiler: "
          which icpx 1>&2
          sh make.sh
          ./bin/test ~[ignore] --abort --duration yes --warn NoAssertions
