name: CI

on: 
  workflow_dispatch:

env:
  ONEAPI_COMPILER_URL: |
    https://registrationcenter-download.intel.com/akdlm/IRC_NAS/74587994-3c83-48fd-b963-b707521a63f4/l_dpcpp-cpp-compiler_p_2024.2.1.79_offline.sh
  ONEAPI_COMPILER_INSTALL: |
    l_dpcpp-cpp-compiler_p_2024.2.1.79_offline.sh

jobs:
  Intel_OneAPI_ICPX:
    runs-on: ubuntu-20.04
    steps:

      - name: Download Compiler installer
        run: |
          wget $ONEAPI_COMPILER_URL

      - name: Install Compiler
        run: |
          sudo sh ./$ONEAPI_COMPILER_INSTALL -a \
          --silent --cli --eula accept --install-dir /opt/intel/oneapi/

      - name: Set up Intel environment variables
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh

      - name: Checkout votess
        uses: actions/checkout@v2

      - name: Build votess
        run: |
          sh make.sh
          ./bin/test ~[ignore] --abort --duration yes --warn NoAssertions
