name: CI

on: 
  workflow_dispatch:

jobs:
  prereq_intel_oneapi:
    runs-on: ubuntu-20.04
    steps:
      - name: Cache OneAPI Compiler installer
        id: cache-oneapi-installer
        uses: actions/cache@v3
        with:
          path: l_dpcpp-cpp-compiler_p_2024.2.1.79_offline.sh
          key: ${{ runner.os }}-oneapi-installer-${{ hashFiles('l_dpcpp-cpp-compiler_p_2024.2.1.79_offline.sh') }}

      - name: Download Compiler installer
        if: steps.cache-oneapi-installer.outputs.cache-hit != 'true'
        run: |
          wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/74587994-3c83-48fd-b963-b707521a63f4/l_dpcpp-cpp-compiler_p_2024.2.1.79_offline.sh

      - name: Install Compiler
        run: |
          sudo sh ./l_dpcpp-cpp-compiler_p_2024.2.1.79_offline.sh -a \
          --silent --cli --eula accept --install-dir /opt/intel/oneapi/

      - name: Cache OneAPI Installation
        id: cache-oneapi-installation
        uses: actions/cache@v3
        with:
          path: /opt/intel/oneapi/
          key: ${{ runner.os }}-oneapi-install-${{ hashFiles('l_dpcpp-cpp-compiler_p_2024.2.1.79_offline.sh') }}

      - name: Restore OneAPI Installation
        if: steps.cache-oneapi-installation.outputs.cache-hit != 'true'
        run: echo "No cache found, installation will proceed."

      - name: Set up Intel environment variables
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh

      - name: Checkout votess
        uses: actions/checkout@v2

      - name: Build votess
        run: |
          sh make.sh
          ./bin/test ~[ignore] --abort --duration yes --warn NoAssertions

