name: CI

on: 
  workflow_dispatch:

jobs:
  prereq_intel_oneapi:
    runs-on: ubuntu-20.04
    steps:  # Added 'steps:' here
      - name: Cache OneAPI HPCkit installer
        id: cache-oneapi
        uses: actions/cache@v3
        with:
          path: l_HPCKit_p_2024.2.1.79.sh
          key: ${{ runner.os }}-oneapi-${{ hashFiles('l_HPCKit_p_2024.2.1.79.sh') }}

      - name: Download OneAPI HPCkit installer if not cached
        if: steps.cache-oneapi.outputs.cache-hit != 'true'
        run: |
          wget -O l_HPCKit_p_2024.2.1.79.sh https://registrationcenter-download.intel.com/akdlm/IRC_NAS/d461a695-6481-426f-a22f-b5644cd1fa8b/l_HPCKit_p_2024.2.1.79.sh

      - name: Install OneAPI HPCkit
        run: |
          sudo sh ./l_HPCKit_p_2024.2.1.79.sh -a \
          --silent --eula accept --install-dir /opt/intel/oneapi/

  build:
    needs: prereq_intel_oneapi
    runs-on: ubuntu-20.04
    steps:  # Added 'steps:' here
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Intel environment variables
        run: |
          source /opt/intel/oneapi/setvars.sh
          sh make.sh
