name: Draft PDF
on:
  push:
    paths:
      - joss/**
      - .github/workflows/joss.yml
jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: joss/paper.md
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: joss/paper.pdf
      - name: Commit PDF to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: '(auto) Paper PDF Draft'
          add: joss/paper.pdf
      - name: Upload TeX
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: joss/paper.tex
      - name: Commit TeX to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: '(auto) Paper PDF Draft'
          add: joss/paper.tex
